accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path('', views.hello, name="hello"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]
    

esteban/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),

    
    path('accounts/', include('accounts.urls')), 
]

accounts/models.py
from django.db import models

# Create your models here.
class User(models.Model):  # 1
    user_id = models.CharField(max_length=64)
    user_name = models.CharField(max_length=64)
    user_email = models.EmailField(max_length=64)
    password = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self): # 2
        return self.username

    class Meta: # 3
        db_table = 'community_user'
        verbose_name = '커뮤니티 사용자'
        verbose_name_plural = '커뮤니티 사용자'

board/models.py
from django.db import models

# Create your models here.

accounts/views.py
# from django.shortcuts import render

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def hello(request):
    return render(request, 'accounts/hello.html')
    #qqq



def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:hello')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('accounts:hello')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('accounts:hello')

board/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/hello.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <body>

    <head>
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

    {% if user.is_authenticated %}
      <h2>환영합니다! {{ user.username }} 님!</h2>
      <a href="{% url 'accounts:logout' %}" class="login-button">로그아웃</a>
    {% else %}
      <h2>안녕하세요!</h2>
      <p>환영합니다!</p>
      <a href="{% url 'accounts:login' %}" class="login-button">로그인</a>
      <a href="{% url 'accounts:signup' %}" class="login-button">회원가입</a>
    {% endif %}
    
  </body>
{% endblock %}

accounts/templates/accounts/login.html
<h2>로그인</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">로그인</button>
</form>

accounts/templates/accounts/signup.html
<h2>회원가입</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">가입하기</button>
</form>

templates/base.html
<!DOCTYPE html>
<html lang="ko">
  {% include 'head.html' %}
  <body>
    {% include 'header.html' %}
    
    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
  </body>
</html>

templates/head.html
<head>
    <meta charset="UTF-8">
    <title>ESTEBAN</title>
</head>